"""Publication-oriented visualizations generated only from executed results."""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


def plot_loglog_learning_curve(results: pd.DataFrame, png_path: str | Path, pdf_path: str | Path) -> None:
    """Write double-logarithmic validation-MAE learning-curve figures.

    `results` must contain `training_size`, `validation_mae_mean`, and optional
    `validation_mae_std` columns generated by the executable learning-curve code.
    """
    required = {"training_size", "validation_mae_mean"}
    missing = required.difference(results.columns)
    if missing:
        raise KeyError(f"Learning curve results missing columns: {sorted(missing)}")
    ordered = results.sort_values("training_size")
    png_path, pdf_path = Path(png_path), Path(pdf_path)
    png_path.parent.mkdir(parents=True, exist_ok=True)
    pdf_path.parent.mkdir(parents=True, exist_ok=True)
    figure, axis = plt.subplots(figsize=(6.8, 4.8))
    errors = ordered["validation_mae_std"] if "validation_mae_std" in ordered.columns else None
    axis.errorbar(
        ordered["training_size"],
        ordered["validation_mae_mean"],
        yerr=errors,
        marker="o",
        capsize=3,
        label="Validation MAE",
    )
    axis.set_xscale("log")
    axis.set_yscale("log")
    axis.set_xlabel("Number of training bi-molecular samples/pairs")
    axis.set_ylabel("Validation MAE")
    axis.set_title("Learning curve")
    axis.grid(True, which="both", alpha=0.25)
    axis.legend()
    figure.tight_layout()
    figure.savefig(png_path, dpi=300)
    figure.savefig(pdf_path)
    plt.close(figure)
